### ISSUE TITLE
Question from a new programmer.

### ISSUE THREAD

**Issue by rockylikespocky** [T-Wong/SearchBot#1]
Hi T-Wong, I'm new on GitHub and an upcoming Computer Science student, I'm new to programming as well. I find your comments very helpful in the code. Thank you for doing all of this. I have some questions for you. I'm assuming you are keeping this BingBot updated. How are you dealing with the random captchas from Bing? Also if possible, a cool feature to have would be a visual counter to see where the search count is at for each account. I would love to see how that would be done in code. Thank you.

**Comment by T-Wong** [comment]
How are you dealing with the random captchas from Bing?

I've never actually encountered a captcha when searching, so I haven't been able to implement anything to counteract that. Although, about a week ago I switched over to using PhantomJS, which is a headless browser, so there wouldn't be an easy way to quickly view the browser and enter it manually. I would probably just add an assert or if isElementPresent right after clicking the search button and if it finds it, just display a GUI popup saying to manually login and put in the captcha and then click start again. But as I said, I haven't encountered this before, so I can't makeup a locator for it, if you do encounter it, it would be great if you could save the page and send me the HTML for it.

Also if possible, a cool feature to have would be a visual counter to see where the search count is at for each account. I would love to see how that would be done in code.

I have thought about this and I have actually done this very thing on another project that isn't publicly available. I used ScheduledExecutorService that ran every second to update the GUI on the eventdispatch thread. The problem with this is that I'm not doing this through any API, so when searching a lot of the metrics will have to be guessed based on how many searches done and I don't want to give false information, so I don't give any at all. After thinking, I do think it would be good to add a way to see what account is currently being done, what search it is doing, and how many accounts are left. But again I don't think giving a number of points is a good idea. Thanks for the idea.
